### PR TITLE
Refactor structure

### PR DESCRIPTION
**Pull request by TroyNeubauer**
Flattens structure by moving `code/websitesrc/cybertoolwebsite` to `frontend` and `code/lambda` to just `lambda` to make  things easier to navigate.

Also removes `code/package-lock.json` which which wasn't used by anything

### CODE REVIEW

**Review by illusion173 — CHANGES_REQUESTED** [review]
Please see how Amplify deploys github hosted websites. https://docs.aws.amazon.com/amplify/latest/userguide/setting-up-GitHub-access.html Theres a choice if you have a monorepo to have specific deployment folders, its somewhere in aws amplify dashboard. dm me for mroe

**Comment by TroyNeubauer** [comment]
Ah good catch

**Comment by TroyNeubauer** [comment]
I can see the path here, but looks like I cant actually edit it with the edit button or by viewing more. Mind giving it a go?
image

**Comment by TroyNeubauer** [comment]
Updated it
image
This should be good to go

**Comment by TroyNeubauer** [comment]
Also I believe the `cache.paths.node_modules` on the line should above should be `frontend/node_modules/**/*` since there is no node modules in the root directory

**Review by illusion173 — APPROVED** [review]

**Pull request merged**
